import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Check, ChevronDown, ChevronRight, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, Truck, X} from 'lucide-react';
import './styles.css';

const company = {name:'香港添財貿易有限公司', email:'hongkongtiancai@outlook.com', address:'Room 1208, 12/F, Gateway Tower 1, 25 Canton Road, Tsim Sha Tsui, Kowloon, Hong‑Kong'};
const asset = path => path.replace(/\.png$/, '.webp');
const cats = [
  {id:'seating',name:'Seating',cn:'座椅系列',image:'/images/seating.png',alt:'/images/seating-alt.png',alt2:'/images/seating-alt2.png',extra:['/images/seating-3.png','/images/seating-4.png','/images/seating-5.png','/images/seating-6.png','/images/seating-7.png','/images/seating-8.png','/images/seating-9.png'],desc:'Pieces made for slow living'},
  {id:'lighting',name:'Lighting',cn:'灯饰系列',image:'/images/lighting.png',alt:'/images/lighting-alt.png',alt2:'/images/lighting-alt2.png',extra:['/images/lighting-3.png','/images/lighting-4.png','/images/lighting-5.png','/images/lighting-6.png','/images/lighting-7.png','/images/lighting-8.png','/images/lighting-9.png'],desc:'A softer way to see home'},
  {id:'rugs',name:'Rugs & Textiles',cn:'地毯与织物',image:'/images/rugs.png',alt:'/images/rugs-alt.png',alt2:'/images/rugs-alt2.png',extra:['/images/rugs-3.png','/images/rugs-4.png','/images/rugs-5.png','/images/rugs-6.png','/images/rugs-7.png','/images/rugs-8.png','/images/rugs-9.png'],desc:'Texture under every step'},
  {id:'dining',name:'Dining',cn:'餐厅系列',image:'/images/dining.png',alt:'/images/dining-alt.png',alt2:'/images/dining-alt2.png',extra:['/images/dining-3.png','/images/dining-4.png','/images/dining-5.png','/images/dining-6.png','/images/dining-7.png','/images/dining-8.png','/images/dining-9.png'],desc:'Gather around something good'},
  {id:'bedding',name:'Bedding',cn:'卧室系列',image:'/images/bedding.png',alt:'/images/bedding-alt.png',alt2:'/images/bedding-alt2.png',extra:['/images/bedding-3.png','/images/bedding-4.png','/images/bedding-5.png','/images/bedding-6.png','/images/bedding-7.png','/images/bedding-8.png','/images/bedding-9.png'],desc:'Rest, beautifully'},
];
const names = {
 seating:['Walnut Lounge Chair','Arc Bouclé Chair','Lowline Reading Chair','Sculptural Oak Bench','Cane Back Armchair','Pebble Occasional Chair','Studio Dining Chair','Quiet Corner Ottoman','Frame Lounge Chair','Linen Club Chair'],
 lighting:['Hearth Ceramic Lamp','Orion Floor Lamp','Pebble Table Lamp','Arc Paper Pendant','Mori Wall Sconce','Silo Reading Light','Halo Linen Pendant','Stillness Desk Lamp','Dune Ceramic Light','Forma Brass Sconce'],
 rugs:['Oatmeal Handwoven Rug','Olive Line Wool Rug','Sable Flatweave Rug','Mist Tufted Rug','Clay Border Rug','Natural Jute Rug','Quiet Grid Wool Rug','Linen Loop Rug','Dune Runner','Soft Structure Rug'],
 dining:['Cedar Dining Table','Solace Sideboard','Atelier Dining Chair','Mori Extendable Table','Linen Counter Stool','Foundry Bar Cart','Oak Serving Console','Cove Dining Bench','Harvest Cabinet','Plainware Credenza'],
 bedding:['Cloud Linen Duvet','Olive Throw Blanket','Washed Cotton Sheet Set','Loom Pillow Pair','Twill Bed Cover','Waffle Blanket','Piped Linen Pillow','Quiet Night Robe','Natural Fiber Quilt','Hearth Bed Runner']
};
const prices = [498,680,420,760,560,340,890,310,620,740];
const products = cats.flatMap((c,ci)=>names[c.id].map((name,i)=>({id:c.id+'-'+i,name,category:c.id,categoryName:c.name,price:prices[(i+ci)%prices.length],image:[c.image,c.alt,c.alt2,...c.extra][i],tag:i===0?'Bestseller':i===2?'New':''})));

function App(){
 const [cat,setCat]=useState('All pieces'), [cart,setCart]=useState([]), [drawer,setDrawer]=useState(false), [menu,setMenu]=useState(false), [search,setSearch]=useState(''), [page,setPage]=useState(window.location.hash==='#/admin'?'admin':'home'), [pay,setPay]=useState('PayPal');
 const filtered=useMemo(()=>products.filter(p=>(cat==='All pieces'||p.categoryName===cat)&&p.name.toLowerCase().includes(search.toLowerCase())),[cat,search]);
 const total=cart.reduce((s,p)=>s+p.price*p.qty,0);
 const add=(p,buy=false)=>{setCart(c=>{const x=c.find(i=>i.id===p.id); return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});setDrawer(true);if(buy)setPage('checkout')};
 const change=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:Math.max(0,i.qty+d)}:i).filter(i=>i.qty));
 if(page==='checkout') return <Checkout cart={cart} total={total} pay={pay} setPay={setPay} setPage={setPage}/>;
 if(page==='admin') return <AdminPage setPage={setPage}/>;
 if(page==='collection') return <CollectionPage selected={cat} setSelected={setCat} setPage={setPage}/>;
 if(page!=='home') return <InfoPage page={page} setPage={setPage}/>;
 return <div className="site">
  <div className="announcement">Complimentary delivery on orders over $500 <ArrowRight size={14}/></div>
  <header><button className="icon-btn mobile" onClick={()=>setMenu(!menu)}><Menu/></button><a className="logo" href="#top" onClick={()=>setPage('home')}>TIANCAI<span>HOME ESSENTIALS</span></a><nav className={menu?'open':''}><a href="#shop-all" onClick={e=>{e.preventDefault();setCat('All pieces');setMenu(false);setPage('collection')}}>Shop all</a>{cats.map(c=><a href={'#'+c.id} key={c.id} onClick={e=>{e.preventDefault();setCat(c.name);setMenu(false);setPage('collection')}}>{c.name}</a>)}<a href="#about" onClick={e=>{e.preventDefault();setPage('about');setMenu(false)}}>Our story</a></nav><div className="head-actions"><div className="search"><Search size={17}/><input placeholder="Search" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="bag" onClick={()=>setDrawer(true)}><ShoppingBag size={19}/><span>{cart.reduce((s,p)=>s+p.qty,0)}</span></button></div></header>
  <main>
   <section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14}/> THE ART OF LIVING WELL</p><h1>Make room for<br/><em>what matters.</em></h1><p className="hero-text">Thoughtful furniture and considered objects for a home that feels entirely your own.</p><button className="dark-btn" onClick={()=>document.getElementById('shop').scrollIntoView({behavior:'smooth'})}>Explore the collection <ArrowRight size={16}/></button></div><div className="hero-image"><img src={asset('/images/seating.png')}/><div className="image-note">01 / 05<br/><span>Natural materials, lasting forms</span></div></div></section>
   <section className="trust"><div><Truck/> <span>Made to order<br/><small>Thoughtfully produced</small></span></div><div><Check/> <span>Considered quality<br/><small>Built for everyday life</small></span></div><div><span className="trust-icon">HK</span> <span>Hong Kong based<br/><small>Care from our studio</small></span></div></section>
   <section className="intro"><p className="eyebrow">A QUIETER KIND OF LUXURY</p><h2>Objects with a point of view.</h2><p>We believe a well-made home is a collection of small decisions. Tactile materials, honest forms, and the pleasure of things that grow more beautiful with time.</p></section>
   <section className="category-grid">{cats.map((c,i)=><button className={'category-card '+(i===0?'large':'')} key={c.id} onClick={()=>{setCat(c.name);document.getElementById('shop').scrollIntoView({behavior:'smooth'})}}><img src={asset(c.image)}/><span><b>{c.name}</b><small>{c.desc}</small></span><ArrowRight/></button>)}</section>
   <section id="shop" className="shop"><div className="section-head"><div><p className="eyebrow">THE COLLECTION</p><h2>Find your everyday.</h2></div><div className="filters"><button className={cat==='All pieces'?'active':''} onClick={()=>setCat('All pieces')}>All pieces</button>{cats.map(c=><button key={c.id} className={cat===c.name?'active':''} onClick={()=>setCat(c.name)}>{c.name}</button>)}</div></div><div className="product-grid">{filtered.map(p=><ProductCard key={p.id} p={p} add={add}/>)}</div></section>
   <section className="newsletter"><div><p className="eyebrow">NOTES FROM HOME</p><h2>A little more considered.</h2><p>New collections, studio notes, and ideas for living well. No noise, just good things.</p></div><div className="signup"><input placeholder="Your email address"/><button className="dark-btn">Sign me up <ArrowRight size={16}/></button></div></section>
  </main><Footer setPage={setPage} setCat={setCat}/>{drawer&&<CartDrawer cart={cart} total={total} close={()=>setDrawer(false)} change={change} setPage={setPage}/>}</div>
}
function CollectionPage({selected,setSelected,setPage}){const [cart,setCart]=useState([]),[drawer,setDrawer]=useState(false);const total=cart.reduce((s,p)=>s+p.price*p.qty,0);const filtered=products.filter(p=>selected==='All pieces'||p.categoryName===selected);const add=(p,buy=false)=>{setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});setDrawer(true);if(buy)setPage('checkout')};const change=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:Math.max(0,i.qty+d)}:i).filter(i=>i.qty));return <div className="collection-page"><header><a className="logo" onClick={()=>setPage('home')}>TIANCAI<span>HOME ESSENTIALS</span></a><button className="bag" onClick={()=>setDrawer(true)}><ShoppingBag size={19}/><span>{cart.reduce((s,p)=>s+p.qty,0)}</span></button></header><main><div className="collection-intro"><button className="back" onClick={()=>setPage('home')}>← Back to home</button><p className="eyebrow">THE COLLECTION</p><h1>{selected==='All pieces'?'Shop all':selected}</h1><p>{selected==='All pieces'?'Every considered piece, together in one place.':`Furniture and objects selected for ${selected.toLowerCase()}.`}</p></div><div className="collection-tabs"><button className={selected==='All pieces'?'active':''} onClick={()=>setSelected('All pieces')}>All pieces</button>{cats.map(c=><button key={c.id} className={selected===c.name?'active':''} onClick={()=>setSelected(c.name)}>{c.name}</button>)}</div><div className="collection-grid">{filtered.map(p=><ProductCard key={p.id} p={p} add={add}/>)}</div></main><Footer setPage={setPage} setCat={setSelected}/>{drawer&&<CartDrawer cart={cart} total={total} close={()=>setDrawer(false)} change={change} setPage={setPage}/>}</div>}
function ProductCard({p,add}){return <article className="product"><div className="product-image"><img src={asset(p.image)}/>{p.tag&&<label>{p.tag}</label>}<button className="quick" onClick={()=>add(p)}>Add to cart <Plus size={15}/></button></div><div className="product-meta"><div><h3>{p.name}</h3><p>{p.categoryName}</p></div><strong>${p.price.toLocaleString()}</strong></div><button className="buy-now" onClick={()=>add(p,true)}>Buy Now — ${p.price.toLocaleString()}</button></article>}
function CartDrawer({cart,total,close,change,setPage}){return <div className="overlay"><aside className="drawer"><div className="drawer-top"><div><p className="eyebrow">YOUR BAG</p><h2>{cart.length?`${cart.length} piece${cart.length>1?'s':''}`:'Your bag is empty'}</h2></div><button className="icon-btn" onClick={close}><X/></button></div>{cart.length?<><div className="cart-items">{cart.map(p=><div className="cart-item" key={p.id}><img src={asset(p.image)}/><div><b>{p.name}</b><small>{p.categoryName}</small><strong>${(p.price*p.qty).toLocaleString()}</strong><div className="qty"><button onClick={()=>change(p.id,-1)}><Minus size={13}/></button>{p.qty}<button onClick={()=>change(p.id,1)}><Plus size={13}/></button></div></div></div>)}</div><div className="drawer-bottom"><div><span>Subtotal</span><b>${total.toLocaleString()}</b></div><small>Shipping and taxes calculated at checkout.</small><button className="dark-btn full" onClick={()=>{close();setPage('checkout')}}>Continue to checkout <ArrowRight size={16}/></button></div></>:<p className="empty">Your next favorite piece is waiting in the collection.</p>}</aside></div>}
function Checkout({cart,total,pay,setPay,setPage}){return <div className="checkout-page"><header><a className="logo" onClick={()=>setPage('home')}>TIANCAI<span>HOME ESSENTIALS</span></a><span className="secure">Secure checkout · 256-bit SSL</span></header><div className="checkout-wrap"><div><button className="back" onClick={()=>setPage('home')}>← Continue shopping</button><h1>Complete your order.</h1><div className="form-card"><h3>Contact information</h3><input placeholder="Email address"/><h3>Delivery address</h3><div className="two"><input placeholder="First name"/><input placeholder="Last name"/></div><input placeholder="Address"/><div className="two"><input placeholder="City"/><input placeholder="Postal code"/></div><select><option>Hong Kong SAR</option><option>United States</option><option>United Kingdom</option></select></div><div className="form-card"><h3>Payment method</h3><div className="payment-options">{['PayPal','Visa','Credit Card'].map(x=><button key={x} className={pay===x?'selected':''} onClick={()=>setPay(x)}><span className={'pay-icon '+x.replace(' ','').toLowerCase()}>{x==='PayPal'?'P':x==='Visa'?'V':'▣'}</span>{x}{pay===x&&<Check size={15}/>}</button>)}</div>{pay==='Credit Card'&&<div className="card-fields"><input placeholder="Card number"/><div className="two"><input placeholder="MM / YY"/><input placeholder="CVC"/></div></div>}<button className="dark-btn full pay-btn" onClick={()=>alert('Demo checkout: connect your payment provider keys to complete payment.')}>Pay ${total.toLocaleString()} <ArrowRight size={16}/></button></div></div><aside className="order-summary"><p className="eyebrow">ORDER SUMMARY</p>{cart.length?cart.map(p=><div className="summary-item" key={p.id}><img src={asset(p.image)}/><div><b>{p.name}</b><span>Qty {p.qty}</span></div><strong>${(p.price*p.qty).toLocaleString()}</strong></div>):<p>No items yet.</p>}<div className="summary-total"><span>Subtotal</span><b>${total.toLocaleString()}</b></div><div className="summary-total"><span>Delivery</span><b>Complimentary</b></div><div className="summary-total grand"><span>Total</span><b>${total.toLocaleString()}</b></div></aside></div></div>}
function InfoPage({page,setPage}){const data={about:['About us','A home is made of the things you choose to keep.'],shipping:['Shipping policy','Every piece is packed with care and dispatched from our Hong Kong studio.'],tracking:['Order tracking','Your tracking link will be emailed as soon as your order leaves our studio.'],terms:['Terms of Service','These terms set out the agreement between you and 香港添財貿易有限公司.'],privacy:['Privacy policy','We collect only the information needed to process orders and support your experience.'],returns:['Returns & refunds','If something is not right, contact us within 14 days of delivery.'],cancellation:['Cancellation policy','Orders may be cancelled within 24 hours, before production or dispatch begins.'],dmca:['DMCA','If you believe content on this site infringes your rights, contact our team with the relevant details.']}[page]||['Information','']; return <div className="info-page"><header><a className="logo" onClick={()=>setPage('home')}>TIANCAI<span>HOME ESSENTIALS</span></a><button className="back" onClick={()=>setPage('home')}>← Back to shop</button></header><main><p className="eyebrow">TIANCAI HOME ESSENTIALS</p><h1>{data[0]}</h1><p className="lead">{data[1]}</p><div className="legal-copy"><p>香港添財貿易有限公司 (“we”, “us” or “our”) is committed to providing a clear, considered experience. Please read this page together with the information shown at checkout.</p><h3>1. Scope</h3><p>These terms apply to purchases made through this website. By placing an order, you confirm that you have read and accepted the applicable terms.</p><h3>2. Products and availability</h3><p>Product descriptions, dimensions, materials and prices are presented as accurately as possible. Availability may change without notice.</p><h3>3. Orders and payment</h3><p>An order is accepted when we send an order confirmation. Payment is processed through the selected payment provider. Prices are shown in USD unless stated otherwise.</p><h3>4. Delivery</h3><p>Delivery estimates are indicative. Delays outside our reasonable control do not create an automatic right to compensation.</p><h3>5. Returns</h3><p>Unused items may be eligible for return under our returns policy. Made-to-order and personalised pieces may be excluded.</p><h3>6–17. General</h3><p>These sections cover cancellations, refunds, intellectual property, privacy, acceptable use, liability, events beyond control, communications, severability, waiver, assignment, governing law and contact. For questions, email {company.email}.</p><h3>Contact</h3><p>{company.name}<br/>{company.address}<br/>{company.email}</p></div></main><Footer setPage={setPage} setCat={()=>{}}/></div>}
function Footer({setPage,setCat}){const openInfo=(e,page)=>{e.preventDefault();setPage(page)};return <footer><div className="footer-main"><div><a className="logo light" href="/" onClick={e=>openInfo(e,'home')}>TIANCAI<span>HOME ESSENTIALS</span></a><p>Thoughtful pieces for a more considered home.</p></div><div><b>Shop</b>{cats.map(c=><a href={'#'+c.id} key={c.id} onClick={e=>{e.preventDefault();setCat?.(c.name);setPage('collection');window.scrollTo(0,0)}}>{c.name}</a>)}</div><div><b>Help</b>{[['shipping','Shipping policy'],['tracking','Order tracking'],['returns','Returns & refunds'],['cancellation','Cancellation policy']].map(x=><a href={'#'+x[0]} key={x[0]} onClick={e=>openInfo(e,x[0])}>{x[1]}</a>)}</div><div><b>Company</b><a href="#about" onClick={e=>openInfo(e,'about')}>About us</a><a href="#terms" onClick={e=>openInfo(e,'terms')}>Terms of Service</a><a href="#privacy" onClick={e=>openInfo(e,'privacy')}>Privacy policy</a><a href="#dmca" onClick={e=>openInfo(e,'dmca')}>DMCA</a></div><div className="footer-contact"><b>Contact</b><strong>{company.name}</strong><span>{company.email}</span><span>{company.address}</span></div></div><div className="footer-bottom"><span>© 2026 {company.name}</span><span>Registered office: {company.address}</span><span>{company.email}</span></div></footer>}
function AdminPage({setPage}){const [ok,setOk]=useState(false),[user,setUser]=useState(''),[pass,setPass]=useState('');return <div className="admin-page"><div className="admin-card"><a className="logo" onClick={()=>setPage('home')}>TIANCAI<span>HOME ESSENTIALS</span></a>{ok?<><p className="eyebrow">STORE ADMIN</p><h1>Good morning.</h1><p className="admin-muted">Your dashboard is ready for products, orders and customer messages.</p><div className="admin-stats"><div><b>50</b><span>Products</span></div><div><b>0</b><span>Open orders</span></div><div><b>$0</b><span>Revenue</span></div></div><button className="dark-btn full" onClick={()=>setPage('home')}>View storefront <ArrowRight size={16}/></button></>:<><p className="eyebrow admin-eyebrow">PRIVATE STORE ADMIN</p><h1>Welcome back.</h1><p className="admin-muted">Sign in to manage your catalog and orders.</p><input value={user} onChange={e=>setUser(e.target.value)} placeholder="Email or username"/><input value={pass} onChange={e=>setPass(e.target.value)} type="password" placeholder="Password"/><button className="dark-btn full" onClick={()=>{if(user==='admin'&&pass==='TCHome2026!')setOk(true);else alert('Demo credentials: admin / TCHome2026!')}}>Sign in <ArrowRight size={16}/></button><button className="back admin-back" onClick={()=>setPage('home')}>← Back to storefront</button></>}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
